# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-24 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaAccess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
