# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_city', models.CharField(max_length=250)),
                ('To_city', models.CharField(max_length=250)),
                ('Price', models.CharField(max_length=6)),
            ],
        ),
    ]
