# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='id',
        ),
        migrations.AddField(
            model_name='cost',
            name='ID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
