# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-20 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0003_auto_20180219_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='J_ID',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
