# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etravel_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=250)),
                ('bus_type', models.CharField(max_length=200)),
                ('dep_time', models.CharField(max_length=10)),
                ('arr_time', models.CharField(max_length=10)),
                ('travel_time', models.CharField(max_length=50)),
                ('ratings', models.CharField(max_length=200)),
                ('seats', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
    ]
