# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-17 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etravel_search', '0002_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='date',
            field=models.CharField(max_length=200),
        ),
    ]
