# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-18 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etravel_search', '0003_auto_20180217_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_City', models.CharField(max_length=250)),
                ('T_City', models.CharField(max_length=250)),
                ('Cost', models.IntegerField()),
            ],
        ),
    ]
