# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-18 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etravel_search', '0004_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='Cost',
            field=models.CharField(max_length=8),
        ),
    ]
