# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etravel_search', '0005_auto_20180218_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cost',
        ),
    ]
