# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etravel_search', '0007_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cost',
        ),
    ]
