# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etravel_search', '0008_delete_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(max_length=10)),
                ('Journey_id', models.CharField(max_length=10)),
            ],
        ),
    ]
