# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etravel_search', '0009_user_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_journey',
            name='Session_id',
            field=models.BooleanField(default=False),
        ),
    ]
