# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-20 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etravel_search', '0010_user_journey_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(max_length=10)),
                ('User_name', models.CharField(max_length=50)),
                ('Credit', models.CharField(max_length=8)),
            ],
        ),
    ]
