# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-28 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etravel_search', '0012_bus_j_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=10)),
            ],
        ),
    ]
