# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-29 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etravel_search', '0013_busid'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='Phone_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
