# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-29 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etravel_search', '0014_passenger_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusID',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
